### ISSUE TITLE
make sure that you add your own projects not copied from others

### ISSUE THREAD

**Issue by javascript-spec** [javascript-spec/hacktoberfest2021#16]

**Comment by Ukesh-dev** [comment]
Can I work on this issue? Would you mind assigning it to me?

**Comment by javascript-spec** [comment]
Sure @Ukesh-dev

**Comment by RishiRajKhanna2511** [comment]
Can you assign it to me . I have a build some project.

**Comment by RishiRajKhanna2511** [comment]
I have build a Javascript piano project .

**Comment by ABeck617** [comment]
Can you please assign me this project

**Comment by aakashjain294** [comment]
I have built an hackerrank automation using javascript and  puppeteer.

**Comment by rupal2711** [comment]
i have made a project using using React and firebase.. can you please assign it to me?

**Comment by itsPrajapat** [comment]
I have made an Weather app using HTML CSS Nodejs JavaScript Please Assign it me sir

**Comment by javascript-spec** [comment]
hope to see you in hacktoberfest 2022 :)
